length: 1.0  # km
p_loss_init: 0.889 #  probability  1 - 0.111
p_loss_length: 0.25  # dB/km
speed_of_light: 214_000  # km/s
dark_count_probability: 1.4e-5  #  probability
detector_efficiency: 1.0  #  probability
visibility: 0.89
num_resolving: False