num_qubits: 2

# coherence times (same for each qubit), all in ns
T1: 1e99  # Disabled amplitude dampening
T2: 85e6  # 85 ms

# gate execution times, all in ns
init_time: 36_000
single_qubit_gate_time: 26_600
two_qubit_gate_time: 107_000
measure_time: 1_500_000

# noise model, all probabilities
single_qubit_gate_depolar_prob: 0.02
two_qubit_gate_depolar_prob: 0.1