length: 1.0  # km
p_loss_init: 0.99949  # probability, 1 - 5.1e−4
p_loss_length: 0.25  # dB/km
speed_of_light: 214_000  # km/s
dark_count_probability: 1.5e-7  # probability
detector_efficiency: 1.0  # probability
visibility: 0.9
num_resolving: False